# Generated by Django 3.0.1 on 2019-12-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artwork',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/'),
        ),
    ]
