# Generated by Django 3.0.1 on 2019-12-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_album_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='song',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/'),
        ),
    ]
