# Generated by Django 3.0.1 on 2020-01-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_track_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artwork',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='song',
            field=models.FileField(blank=True, default='', null=True, upload_to='static/'),
        ),
    ]
