# Generated by Django 3.0.1 on 2020-02-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_photos_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
