# Generated by Django 3.0.1 on 2020-02-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200218_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
